[[wallpaper]]
    display = "HDMI2"
    wallpaper = "/home/shail/Pictures/backgrounds/parrot-wallpapers/backgrounds/toxic2.jpg"
    bg = "center"
    bg-color = "black"

[[wallpaper]]
    display = "eDP1"
    wallpaper = "/home/shail/Pictures/backgrounds/wp5582226-neon-samurai-cyberpunk-wallpapers.jpg"
    bg = "max"
    bg-color = "black"

